<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Minimum.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Minimum.Infrastructure.csproj" />
    <ProjectReference Include="..\Persistence\Minimum.Persistence.csproj" />
    <ProjectReference Include="..\Shared\Minimum.Shared.csproj" />
  </ItemGroup>

</Project>
